-- MySQL Script generated by MySQL Workbench
-- Wed Jul  5 20:32:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema diselectricrosdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema diselectricrosdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `diselectricrosdb` DEFAULT CHARACTER SET utf8mb3 ;
USE `diselectricrosdb` ;

-- -----------------------------------------------------
-- Table `diselectricrosdb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diselectricrosdb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nombreU` VARCHAR(45) NOT NULL,
  `barrioU` VARCHAR(45) NOT NULL,
  `municipioU` VARCHAR(45) NOT NULL,
  `correoU` VARCHAR(45) NOT NULL,
  `telefonoU` VARCHAR(45) NOT NULL,
  `direccionU` VARCHAR(45) NOT NULL,
  `contraseñaU` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `correoU_UNIQUE` (`correoU` ASC) VISIBLE,
  UNIQUE INDEX `contraseñaU_UNIQUE` (`contraseñaU` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diselectricrosdb`.`carritoCompras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diselectricrosdb`.`carritoCompras` (
  `idcarritoCompras` INT NOT NULL,
  `cantidadP` INT ZEROFILL NOT NULL,
  `descuentoP` DOUBLE NOT NULL,
  `totalP` DOUBLE NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idcarritoCompras`, `Usuario_idUsuario`),
  INDEX `fk_carritoCompras_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_carritoCompras_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `diselectricrosdb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diselectricrosdb`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diselectricrosdb`.`Administrador` (
  `idAdministrador` INT NOT NULL,
  `nombreA` VARCHAR(45) NOT NULL,
  `correoA` VARCHAR(45) NOT NULL,
  `contraseñaA` VARCHAR(45) NOT NULL,
  `Vendido_idVendido` INT NOT NULL,
  PRIMARY KEY (`idAdministrador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diselectricrosdb`.`PedidoVendido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diselectricrosdb`.`PedidoVendido` (
  `idPedido` INT NOT NULL,
  `fechaEntregaP` TIMESTAMP(6) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `carritoCompras_idcarritoCompras` INT NOT NULL,
  `carritoCompras_Usuario_idUsuario` INT NOT NULL,
  `Administrador_idAdministrador` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_Pedido_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_Pedido_carritoCompras1_idx` (`carritoCompras_idcarritoCompras` ASC, `carritoCompras_Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_PedidoVendido_Administrador1_idx` (`Administrador_idAdministrador` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `diselectricrosdb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_carritoCompras1`
    FOREIGN KEY (`carritoCompras_idcarritoCompras` , `carritoCompras_Usuario_idUsuario`)
    REFERENCES `diselectricrosdb`.`carritoCompras` (`idcarritoCompras` , `Usuario_idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PedidoVendido_Administrador1`
    FOREIGN KEY (`Administrador_idAdministrador`)
    REFERENCES `diselectricrosdb`.`Administrador` (`idAdministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diselectricrosdb`.`AgregaProductoAd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diselectricrosdb`.`AgregaProductoAd` (
  `idAgregarProducto` INT NOT NULL,
  `nombreAp` VARCHAR(45) NOT NULL,
  `marcaAp` VARCHAR(45) NOT NULL,
  `precioUnitarioAp` DOUBLE NOT NULL,
  `cantidadAp` INT ZEROFILL NOT NULL,
  `descripcionAp` VARCHAR(45) NOT NULL,
  `descripcionLAp` VARCHAR(300) NOT NULL,
  `rutaImagenAp` VARCHAR(450) NOT NULL,
  `Administrador_idAdministrador` INT NOT NULL,
  `nameImagenAp` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idAgregarProducto`),
  INDEX `fk_AgregarProductoAd_Administrador1_idx` (`Administrador_idAdministrador` ASC) VISIBLE,
  CONSTRAINT `fk_AgregarProductoAd_Administrador1`
    FOREIGN KEY (`Administrador_idAdministrador`)
    REFERENCES `diselectricrosdb`.`Administrador` (`idAdministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diselectricrosdb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diselectricrosdb`.`Producto` (
  `idProducto` INT NOT NULL,
  `carritoCompras_idcarritoCompras` INT NOT NULL,
  `carritoCompras_Usuario_idUsuario` INT NOT NULL,
  `AgregaProductoAd_idAgregarProducto` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_Producto_carritoCompras1_idx` (`carritoCompras_idcarritoCompras` ASC, `carritoCompras_Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_Producto_AgregaProductoAd1_idx` (`AgregaProductoAd_idAgregarProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_carritoCompras1`
    FOREIGN KEY (`carritoCompras_idcarritoCompras` , `carritoCompras_Usuario_idUsuario`)
    REFERENCES `diselectricrosdb`.`carritoCompras` (`idcarritoCompras` , `Usuario_idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_AgregaProductoAd1`
    FOREIGN KEY (`AgregaProductoAd_idAgregarProducto`)
    REFERENCES `diselectricrosdb`.`AgregaProductoAd` (`idAgregarProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diselectricrosdb`.`MedioPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diselectricrosdb`.`MedioPago` (
  `idMedioPago` INT NOT NULL,
  `tipoPago` VARCHAR(20) NOT NULL,
  `numCuenta` INT ZEROFILL NOT NULL,
  `expiracion` DATE NOT NULL,
  `proveedor` VARCHAR(45) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `efectivo` INT NOT NULL,
  `carritoCompras_idcarritoCompras` INT NOT NULL,
  `carritoCompras_Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idMedioPago`, `Usuario_idUsuario`),
  INDEX `fk_MedioPago_Usuario_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_MedioPago_carritoCompras1_idx` (`carritoCompras_idcarritoCompras` ASC, `carritoCompras_Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_MedioPago_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `diselectricrosdb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MedioPago_carritoCompras1`
    FOREIGN KEY (`carritoCompras_idcarritoCompras` , `carritoCompras_Usuario_idUsuario`)
    REFERENCES `diselectricrosdb`.`carritoCompras` (`idcarritoCompras` , `Usuario_idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diselectricrosdb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diselectricrosdb`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `tipoCategoria` VARCHAR(45) NOT NULL,
  `AgregarProductoAd_idAgregarProducto` INT NOT NULL,
  PRIMARY KEY (`idCategoria`, `AgregarProductoAd_idAgregarProducto`),
  INDEX `fk_Categoria_AgregarProductoAd1_idx` (`AgregarProductoAd_idAgregarProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Categoria_AgregarProductoAd1`
    FOREIGN KEY (`AgregarProductoAd_idAgregarProducto`)
    REFERENCES `diselectricrosdb`.`AgregaProductoAd` (`idAgregarProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

